services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DB_HOST: 172.17.0.1
      DB_PORT: 5432
      DB_NAME: parser_db
      DB_USER: postgres
      DB_PASSWORD: postgres
    networks:
      - mynet
    restart: unless-stopped

networks:
  mynet:
    driver: bridge
    
