version: "3.10"

services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      # Example environment variables
      - ENV=production
    restart: always
    volumes:
      - ./app.log:/app/app.log
